### ISSUE TITLE
run-e2e script CHECK_DURATION: unbound variable

### ISSUE THREAD

**Issue by rjsadow** [kubernetes-sigs/hydrophone#104]
An issue in our `hack/run-e2e.sh` script is causing periodic jobs to fail.  The variable `CHECK_DURATION` should be initialized similar to the other variables around https://github.com/kubernetes-sigs/hydrophone/blob/main/hack/run-e2e.sh#L70-L82 or have a default value set on line 54. 

```
hack/run-e2e.sh: line 54: CHECK_DURATION: unbound variable
```

If anyone wants to take a look at this, please feel free to assign yourself to the issue. And if there are any questions, reach out in this issue or to me on slack at @rjsadow

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/hydrophone-e2e-check/1747715074929201152

**Comment by reetasingh** [comment]
I can look into this

**Comment by NaveenGokavarapu19** [comment]
i would like to look at this

**Comment by NaveenGokavarapu19** [comment]
hii @reetasingh can we both look at the issue. If it ok for you
