### ISSUE TITLE
`#hydrophone` should be added to the README

### ISSUE THREAD

**Issue by rjsadow** [kubernetes-sigs/hydrophone#111]
The `#hydrophone` slack channel was recently created. We need to update the readme https://github.com/kubernetes-sigs/hydrophone/blob/main/README.md?plain=1#L121 with the new slack channel and make sure it's apparent that this is the preferred channel to reach out on. We can keep #sig-testing and #sig-conformance as they're very related and relevant to this project. 

If anyone wants to take a look at this, please feel free to assign yourself to the issue. And if there are any questions, reach out in this issue or to me on slack at @rjsadow

/good-first-issue

**Comment by UtkarshUmre** [comment]
Hey @rjsadow  can fix this issue if nobody's working on it?

**Comment by rjsadow** [comment]
I believe @AryanSharma9917 is working on it.
