### ISSUE TITLE
Remove `cfg` and `config` from `PrintListImages()`

### ISSUE THREAD

**Issue by rakshitgondwal** [kubernetes-sigs/hydrophone#112]
There are two unused parameters `cfg` and `config` in the `PrintListImages()` function under `pkg/service/list_images.go`.
Since these are unused, it would be better to remove them from the function.

/good-first-issue

**Comment by BalaadityaPatanjali** [comment]
Hey ! i would like to work on this issue ! @rakshitgondwal
