### ISSUE TITLE
Show some progress info for the tests

### ISSUE THREAD

**Issue by letmerecall** [kubernetes-sigs/hydrophone#118]
## What's the issue?
While running the test we don't show any progress bar or any other info to know that the tests are running. Since the test suite takes a while to run, it sometimes feels like the process hangs and there's no progress at all.

(screenshot showing the same content even after 30 minutes)
<img width="1502" alt="Screenshot 2024-01-20 at 5 04 02 PM" src="https://github.com/kubernetes-sigs/hydrophone/assets/19938474/b77c4e51-8403-4649-8fcd-49926d7296d9">

Some ideas to tackle this might be adding a progress animation like the `kind` does when spinning up a cluster OR simply setting the user expectations that the process might take a while.

## How to reproduce
Run the following command
```shell
bin/hydrophone --conformance
```

**Comment by rjsadow** [comment]
I'm not sure I agree that we should add a progress bar. 

1. All of the output of conformance image is just passed through to hydrophone, so we don't have any control or insight into the number of specs that have run or are to be run at any given time. And as far as I know that's not a flag or option that we can pass the conformance image. 
2. Any attempts or additions to making a progress bar or status bar would add (in my opinion) additional bloat to the package for minimal benefit. One of the goals of hydrophone is to keep it as lightweight as possible.
3. While there's no direct status provided, the command does not return until the pod/tests have finished, so as long as the user is not back at a command prompt it's likely safe to assume the command is still running. 

@letmerecall let me know your thoughts and if you think my assessment is reasonable. 

@dims curious to get your input on this as well.

**Comment by dims** [comment]
+1 to no progress bar. There isn't a good way to thread it through all the way in and it's extremely difficult to predict how long it will take or how far we are along.

if it is just a infinite spinner that does not show any indication of above, that may be a possibility since all we need to know for that is ... "is this conformance pod complete or not"

**Comment by letmerecall** [comment]
@rjsadow I agree on not to make it complicated.
@dims yes, an infinite spinner will do the work. The idea was to have 'any' hint/info that the tests are running.
