### ISSUE TITLE
Redundant error check in client.PrintE2ELogs() function

### ISSUE THREAD

**Issue by reetasingh** [kubernetes-sigs/hydrophone#123]
The error check on https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/client/check.go#L63 seems redundant since it will always be nil given that within the `for loop `a new err variable is initialized everytime https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/client/check.go#L55

**Comment by rjsadow** [comment]
I agree, we can remove that block without issue.

**Comment by rjsadow** [comment]
@reetasingh are you interesting in updating this block?

**Comment by reetasingh** [comment]
@rjsadow yes, will raise a PR
