### ISSUE TITLE
Add a brew repo

### ISSUE THREAD

**Issue by cprivitere** [kubernetes-sigs/hydrophone#142]
Hey all, would like to start using this instead of sonobuoy, however you don't have a brew package yet. Would love to see that get added.

**Comment by dims** [comment]
@cprivitere no we don't yet. would you have cycles to help with that? (would be awesome!!)

**Comment by reetasingh** [comment]
@dims @cprivitere @rjsadow I am interested in working on this . I can assign this issue to myself if @cprivitere is fine with that

**Comment by cprivitere** [comment]
I sure don't mind. I don't really have the cycles at the moment.

**Comment by reetasingh** [comment]
PR opened https://github.com/Homebrew/homebrew-core/pull/162309

**Comment by reetasingh** [comment]
@cprivitere @dims @rjsadow looks like we need more adoption for hydrophone to make it available on homebrew , see comment https://github.com/Homebrew/homebrew-core/pull/162309#issuecomment-1937488462

**Comment by dims** [comment]
@reetasingh no worries. if enough folks chime in here or there (or we get some data on downloads) then we can ask them to revisit. thanks for trying!

**Comment by dims** [comment]
(ya, no need for that personal tap thing now)

**Comment by cprivitere** [comment]
When they say personal tap they just mean "not managed by the brew maintainers". This is what I expected us to create, a brewfile inside this repo that people could tap with brew tap kubernetes-sigs/hydrophone and use to get updates. goreleaser can create them for you.

**Comment by dims** [comment]
@cprivitere that does not sound too bad! :)

**Comment by reetasingh** [comment]
@cprivitere I have created a draft PR https://github.com/kubernetes-sigs/hydrophone/issues/142 PTAL
