### ISSUE TITLE
hydrophone --cleanup is broken

### ISSUE THREAD

**Issue by reetasingh** [kubernetes-sigs/hydrophone#149]
We are not setting default value for namespace flag when calling  `hydrophone --cleanup `  as a result its getting a blank namespace https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/service/init.go#L325
```
reeta@Reetas-MacBook-Pro homebrew-core % hydrophone --cleanup
17:35:42 INF API endpoint : https://127.0.0.1:50108
17:35:42 INF Server version : version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:42:59Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}
17:35:42 ERR an empty namespace may not be set when a resource name is provided
reeta@Reetas-MacBook-Pro homebrew-core % 
```

**Comment by Bharadwajshivam28** [comment]
Hey @reetasingh  

I also faced the same issue before but i thought we need to pass the namespace.. like there will be no namespace by default....
![Screenshot from 2024-02-11 07-20-19](https://github.com/kubernetes-sigs/hydrophone/assets/108119109/77cb775e-edee-46f2-bb76-494bf5b66edd)

we can pass namespace by default so one not enters then also that namespace should be there....

If possible can i tackle this issue?

**Comment by reetasingh** [comment]
> Hey @reetasingh
> 
> I also faced the same issue before but i thought we need to pass the namespace.. like there is be no namespace by default....
> 
> ![Screenshot from 2024-02-11 07-20-19](https://private-user-images.githubusercontent.com/108119109/303893797-77cb775e-edee-46f2-bb76-494bf5b66edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MTcwMjAsIm5iZiI6MTcwNzYxNjcyMCwicGF0aCI6Ii8xMDgxMTkxMDkvMzAzODkzNzk3LTc3Y2I3NzVlLWVkZWUtNDZmMi1iYjc2LTQ5NGJmNWI2NmVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwMTU4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmQ1OTFhYjYxMjdkNWQ5NDQxZTg4YjYxZDdiZjE1NTE5ZGExNjc2OTE3NGFiM2I3YWI0ZGIyMDQ3MTNkMDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rLgRGiGJd9eLaeahYxadH1-QpBdhZMbzuu8s0hhk9xQ)
> 
> we can pass namespace by default so one not enters then also that namespace should be there....
> 
> If possible can i tackle this issue?


Hi @Bharadwajshivam28 feel free to assign this to yourself

**Comment by Bharadwajshivam28** [comment]
Thanks.. @reetasingh .

I am new here can you tell me that the default ns name. I guess it will be` conformance `
