### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by letmerecall** [kubernetes-sigs/hydrophone#151]
## What's the issue?

There're 2 broken links in the README.md which are not resolving to correct resources:

1. contributor guide: https://sigs.k8s.io/hydrophone/blob/main/CONTRIBUTING.md
2. filing an issue: https://sigs.k8s.io/hydrophone/issues/new

**Comment by UtkarshUmre** [comment]
Hey @letmerecall  could you assign this to me?

**Comment by letmerecall** [comment]
Feel free to take it @UtkarshUmre 

/assign @UtkarshUmre
