### ISSUE TITLE
Improve logging for resource creation

### ISSUE THREAD

**Issue by rakshitgondwal** [kubernetes-sigs/hydrophone#161]
When a resource already exists, such as `clusterrole` etc, we log both:
```
21:54:37 INF clusterrole already exist conformance-serviceaccount
21:54:37 INF clusterrole created 
```
which is somewhat misleading. This should be fixed i.e. if a resource exists, we should only log already exists and if it gets created, we should log it got created.

**Comment by Bharadwajshivam28** [comment]
Hey @rakshitgondwal  Can i work on this issue?
