### ISSUE TITLE
Confusing configuration file

### ISSUE THREAD

**Issue by xrstf** [kubernetes-sigs/hydrophone#175]
Suppose you download Hydrophone and put it somewhere in your `PATH`. You navigate to your project of choice and take a look:

```bash
$ cd ~/myproject
$ hydrophone --help
...
      --output-dir string           directory for logs. (default "/home/xrstf/myproject")
...
```

Cool! So you run it to perform conformance tests:

```bash
$ export KUBECONFIG=...
$ hydrophone --conformance
...
13:30:53 INF Downloading e2e.log to /home/xrstf/myproject/e2e.log...
13:30:53 INF Downloading junit_01.xml to /home/xrstf/myproject/junit_01.xml...
```

Cool! Now let's run the conformance tests for another project:

```bash
$ cd ..
$ cd anotherproject
$ hydrophone --help
...
      --output-dir string           directory for logs. (default "/home/xrstf/anotherproject")
...

$ export KUBECONFIG=...
$ hydrophone --conformance
...
13:30:53 INF Downloading e2e.log to /home/xrstf/myproject/e2e.log...
13:30:53 INF Downloading junit_01.xml to /home/xrstf/myproject/junit_01.xml...
```

And now you'd be confused why your files ended up in a different location.

I think the way a config file works should be handled differently. Silently remembering default values that are path-dependent is IMHO not a good idea. I would never expect a tool to just take my current flags and use them for all future invocations if I don't specify a flag. Especially since I have no real way to opt out of this behaviour.

**Comment by rjsadow** [comment]
I believe this is because of the way cobra creates the config on intiail run. We ran into this once before and I thourhg @rakshitgondwal was able to fix it.

@rakshitgondwal can you take a peek?

/assign @rakshitgondwal

**Comment by rakshitgondwal** [comment]
Sure @rjsadow, will have a look later as I am a little short on bandwidth.

**Comment by xrstf** [comment]
Tell me how we should change it and I can also take a stab at it. :-)

**Comment by reetasingh** [comment]
its because we are reading previous config file and if it already exists we do not overwrite it. see https://github.com/kubernetes-sigs/hydrophone/blob/main/cmd/root.go#L191-L199 
if there is no need to read previous config file we can instead overwrite it every time. 
```
err := viper.WriteConfig()
		if err != nil {
			log.Fatal("Error:", err)
		}
```

**Comment by xrstf** [comment]
I feel uncomfortable hving the config file be auto-generated and then used on the next run. Suppose I run `hydrophone --dry-run` once, the flag gets remembered and on the next invocation it's automatically dry-run. After the first customized invocation of hydrophone, all subsequent runs of `hydrophone --help` would show potentially wrong default values.

IMHO the `--config` should be an explicit flag and additional flags would override what's loaded from the config (i.e. flags have higher precedence than the config file, if a config file is even given). The format and possible flags of the config file should be documented in the readme. There could also be an additional `--save-config` that, if `--config` is given, will write/create it with the values used for that hydrophone run.
