### ISSUE TITLE
Automatic detection of CI environments to disable the spinner

### ISSUE THREAD

**Issue by AverageMarcus** [kubernetes-sigs/hydrophone#210]
When running within CI environments it would be great if Hydrophone could automatically disable the spinner that would cause a lot of unnecessary log output otherwise.

Kind has a similar function to attempt to detect this environment, see https://github.com/kubernetes-sigs/kind/blob/main/pkg/internal/env/term.go

Alternatively, if automated detection is not ideal for whatever reason it'd be nice to have a flag / config to disable the spinner when running hydropone.

**Comment by BenTheElder** [comment]
I think we should also consider piping progress reports from ginkgo instead of using the spinner more generally

The conformance tests take _hours_ and the spinner doesn't give me any indication of when they might be nearing completion.

**Comment by AverageMarcus** [comment]
Big +1 to that! Or at the very least a summary similar to Sonobuoy that lets you know how many have passed/failed/not yet run.

**Comment by aniruddha2000** [comment]
I am a bit unsure, is https://github.com/kubernetes-sigs/kind/blob/78cf0b1102c90e02a6be2afcb92268f50d5121cd/pkg/internal/env/term.go#L47 is supposed to be the CI terminal?

because I tried the code locally and in both cases I saw the spinner, 

> Alternatively, if automated detection is not ideal for whatever reason it'd be nice to have a flag / config to disable the spinner when running hydrophone

This is a pretty easy solution, but I want to ensure it is the other way first.

**Comment by AverageMarcus** [comment]
I've had another thought about how to handle it - what about introducing an `--output` (or maybe `--format`) flag that allows controlling how Hydrophone reports to the user. I can imagine the following options at some point in the future:
* **Spinner** (default, as today)
* **Status** (not sure exactly what to call this) - reports when a test case has passed or failed, something like the following:
	```
	Total: 1234 | Passed: 45 | Failed: 2 | Skipped 146
	Total: 1234 | Passed: 46 | Failed: 2 | Skipped 146
	Total: 1234 | Passed: 46 | Failed: 2 | Skipped 147
	```
* **Full / Verbose** - Streams the full Ginkgo output as [suggested](https://github.com/kubernetes-sigs/hydrophone/issues/210#issuecomment-2305573792) by @BenTheElder

**Comment by rjsadow** [comment]
I love the idea but I'm not sure if we'll be able to since we don't currently have much control or insight over the output of the conformance pod. Maybe there's some shenanigans we can do if we stream the verbose output to a buffer and parse it.

**Comment by AverageMarcus** [comment]
Maybe it's worth taking a look at how Sonobuoy handles that part? I know it has an output mode that produces a json object with the passed/failed/skipped/etc.

**Comment by Bharadwajshivam28** [comment]
@rjsadow Hey I can try on fixing this issue. We can disable spinner when running in CI environments

**Comment by paul-vd** [comment]
Same issue here, would by nice to be able to globally disable it during CI

**Comment by Bharadwajshivam28** [comment]
@rjsadow I guess for now we can disable the Spinner when running in Github Actions CI

**Comment by BenTheElder** [comment]
> I am a bit unsure, is https://github.com/kubernetes-sigs/kind/blob/78cf0b1102c90e02a6be2afcb92268f50d5121cd/pkg/internal/env/term.go#L47 is supposed to be the CI terminal?
>
> because I tried the code locally and in both cases I saw the spinner,

This is a bit vague / hard to respond to, to be clear: that code doesn't directly control any spinners, it returns true if the terminal should be fine to use fancy formatting like spinners. It checks a number of standard environment variables and lots of people are using kind in github actions and other CI environments. (e.g. see the logs in https://github.com/kubernetes-sigs/kubebuilder/actions/runs/11140456098/job/30959258694)

The code comments link to documentation for each of the things we check.
