### ISSUE TITLE
conformance namespace can't have podSecurity set to baseline

### ISSUE THREAD

**Issue by camaeel** [kubernetes-sigs/hydrophone#217]
e2e-conformance-test pod running in namespace conformance requires more privileges to run. 
Kubernetes clusters with PodSecurity set to enforce baseline don't allow to run this pod. Probably this pod doesn't require any high privilege access to the OS, so maybe few tweaks to the pod configuration can fix this. 

Error message I got:

```
failed to deploy tests: failed to create Pod: pods "e2e-conformance-test" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (containers "conformance-container", "output-container" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "conformance-container", "output-container" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or containers "conformance-container", "output-container" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "conformance-container", "output-container" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

Original ticket: https://github.com/siderolabs/talos/issues/9451

**Comment by rjsadow** [comment]
Our object creations are defined [here](https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/conformance/deploy.go#L36-L193). I think it would be pretty impractical for us to try and update the definitions to be flexible/configurable to meet all needs. I could see a world where setting extra labels or extra annotations applied to all resources are useful and inside the realm of possibility. @dims thoughts?

**Comment by camaeel** [comment]
But this should be pretty simple, just set few settings in pod and container securityContext. 
I can try to provide a PR.

**Comment by rjsadow** [comment]
I'm very happy to take a look at a PR. My concern is keeping the application flexible for any user across any cluster. We need to keep hydrophone object definitions to the bare minimum complexity that's needed for cluster conformance.

**Comment by camaeel** [comment]
I tested in on my private cluster with PodSecurity set to baseline, and it seems to run just fine. 
IMHO those settings should be fine for all clusters. The only thing that could maybe break is access rights to specific directories for writing information, but with dry-run I was able to download junit report and log correctly.

**Comment by BenTheElder** [comment]
> Probably this pod doesn't require any high privilege access to the OS,

The pod hydrophone uses to run the e2e.test binary currently does not (in fact that binary can be run from outside the cluster even, it just needs KUBECONFIG access).

However, to be clear: The pods created during running the conformance tests are allowed to require pretty much anything in the API for the purposes of testing API portability, including elevated permissions.

**Comment by liggitt** [comment]
> However, to be clear: The pods created during running the conformance tests are allowed to require pretty much anything in the API for the purposes of testing API portability, including elevated permissions.

That's true, but I think all the namespaces created *by* e2e tests explicitly set their required pod security level

* https://github.com/kubernetes/kubernetes/blob/9fe41b6198a47d19a598b75eabee3d87b1d0fde1/test/e2e/framework/framework.go#L460-L462
* https://grep.app/search?q=.NamespacePodSecurity&filter[repo][0]=kubernetes/kubernetes

If there's no reason for the conformance pod itself to require escalated host permissions, making it fit inside a baseline namespace sgtm

**Comment by BenTheElder** [comment]
> If there's no reason for the conformance pod itself to require escalated host permissions, making it fit inside a baseline namespace sgtm

+1

Functionally it should only need API access. We should make the hydrophone pod fit baseline.
