### ISSUE TITLE
Refactor Conformance Testing Process

### ISSUE THREAD

**Issue by rjsadow** [kubernetes-sigs/hydrophone#96]
The current process of running `./hydrophone -conformance` is cumbersome as it waits for tests to finish and then grabs the results. This could be more efficient.  It may be more user friendly to refactor some of the testing code into separate sub-commands (e.g., run, get-logs, fetch-files, cleanup).

**Comment by rjsadow** [comment]
This issue will likely involve a bit of a rethinking on how we're handling the command line and default behavior. Some initial thoughts:

- `./hydrophone` should:
  - run run the conformance test suite like with `--conformance`. 
  - pending https://github.com/kubernetes-sigs/hydrophone/issues/94, should run the conformance image on the same version as the test cluster
  - should get the logs and output them to the output-dir
  - should cleanup all of the resources
- `./hydrophone --focus` should remain as is and override setting cfg.Focus. Some work required https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/common/args.go#L139C1-L141 and https://github.com/kubernetes-sigs/hydrophone/blob/main/pkg/common/args.go#L139C1-L141.
- `./hydrophone --cleanup` should remain the same
-  Adding in a `get-logs` or `fetch-logs` option may require some significant rework and design since they're streamed out of the sidecar busybox container. To decouple this we'll need some kind of more persistent storage solution that can be ad-hoc accessed after a run of the conformance image completes. 

Other notes:
- This may be a good time to introduce cobra or some other CLI wrapper to better organize `main.go`

**Comment by SD-13** [comment]
/assign 
I would like to try

**Comment by rjsadow** [comment]
Sounds great @SD-13. It might make more sense to break some of these down into several smaller PRs. We can talk about different aspects as you work on them and figure out what makes sense. Reach out on slack or via this message if you have any issues.

**Comment by rakshitgondwal** [comment]
> This may be a good time to introduce cobra or some other CLI wrapper to better organize `main.go`

+1 to this.

**Comment by rakshitgondwal** [comment]
Hey @SD-13! Wanted to ask you that will you be interested in collaborating on this issue. Like while you are looking into one of the subparts, maybe I can look into the other one?

**Comment by dims** [comment]
@SD-13 please collabroate with @rakshitgondwal and @rjsadow on slack and may be pick up smaller issues / pr(s) as this is a larger piece of work that needs to be broken down.

**Comment by reetasingh** [comment]
Hi @rjsadow @rakshitgondwal from what I see as part of the issue still need to figure out "get-logs or fetch-logs" part . is anyone working on it? and whats the plan?

**Comment by rakshitgondwal** [comment]
> Hi @rjsadow @rakshitgondwal from what I see as scope of the issue still need to figure out "get-logs or fetch-logs" part . is anyone working on it? and whats the plan? I am interested to contribute

Hey @reetasingh, afaik no one is working on that part right now but I am not so sure if we are planning to implement this right now. Maybe Ricky can tell more about this.

**Comment by Bharadwajshivam28** [comment]
Hey 👋
I can also take some part of this issue and work on it with all
